version: '1'

services:
  server:
    build: .
    command: python3 server/server.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
  ui:
    build: ui
    ports:
      - "4200:4200"
    depends_on:
      - server
      